# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

# to adapt depending on the package needs
before_install:
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user 'tensorflow==1.14'
  - pip install --user 'tensorflow-probability==0.7.0'

after_success:
  - Rscript -e 'covr::codecov()'
